### ISSUE TITLE
GUI app crashing: AttributeError [in newer versions of customtkinter]

### ISSUE THREAD

**Issue by SAMAD101** [tushar5526/Autotype#41] opened 2023-02-03 16:22 UTC
**Description:**
In the GUI app, when pressing _Start Typing_ it throws an AttributeError

**How to reproduce:**
Just clone the Repository and open in your IDE, run the GUI using _python3 GUI_script.py_
Type anything in the code/text box, press Start Typing.

**Screenshots:**
![Screenshot_20230202_221508](https://user-images.githubusercontent.com/71956678/216654101-3cdd07e7-d82b-443d-a15a-1fb21bad5773.png)

**My Operating System :** Manjaro (Arch Linux)

**Logs:**
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/sam/.local/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 549, in _clicked
    self._command()
  File "/home/sam/Autotype/GUI_script.py", line 94, in start_typing
    code = self.code.textbox.get("1.0", tk.END)
AttributeError: 'CTkTextbox' object has no attribute 'textbox'

**Comment by RyanWalker277** [comment] 2023-02-03 20:43
Hey @SAMAD101 ! I tried reproducing the issue according to the steps you told me , but I am unable to reproduce the same error as you have reported. Can you check if you are using the version of `tkinter` and `customtkinter` which are specefied in `requirements.txt` by running `pip list` command in your virtual environment? That should give us some more insights on the issue. @tushar5526 @Mr-Sunglasses Can you also try to replicate this issue at your ends so that we can be sure that the bug is persistent.

**Comment by SAMAD101** [comment] 2023-02-04 08:42
Oh, yes. I was using another version of `customtkinter` . It works fine with the version mentioned `requirements.txt` but not with versions above that (I had 5.0.5)

**Comment by RyanWalker277** [comment] 2023-02-04 11:54
> Oh, yes. I was using another version of `customtkinter` . It works fine with the version mentioned `requirements.txt` but not with versions above that (I had 5.0.5)
> 
> I'll update the issue to make it specific for the newer versions of `customtkinter`.

Yeah , that was because the mantainer of customtkinter decided to roll back the textbox attribute in later versions because it was incomplete at his end.It would be better if you could do something that resolves it with newer versions.

**Comment by RyanWalker277** [comment] 2023-02-07 09:57
Closing this for now as `wont-fix`

**Closed** 2023-02-07 09:57 UTC
Labels: bug, wontfix, medium, iwoc
